# Generated by Django 3.1 on 2022-06-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
